spring.application.name=mantenedor
server.port=8085

#spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?sslmode=require
#spring.datasource.username=postgres.nkcqxkbvyczucdbwajsl
#spring.datasource.password=ex6GC704fRWGcZ6N
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mantenedor-ucm?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security.web.*=debug
